### ISSUE TITLE
The item cannot be crafted.

### ISSUE THREAD

**Issue by pil0lo** [Kotori316/InfChest#150]
The item cannot be produced as shown in the video. Why is that?

https://github.com/Kotori316/InfChest/assets/143984023/9aa682e3-fbfb-466f-990e-99d0133a80ec

**Comment by Kotori316** [comment]
* Minecraft version?
* Platform? (Fabric? Forge? NeoForge?)
* Single player or Multi player?

**Comment by pil0lo** [comment]
It is 1.21 fabric.
Even when playing with Fabric version 1.20.6, it was not produced.
Since I couldn't craft it, I collected the necessary materials, went into game mode, deleted the materials, and created the item.

**Comment by Kotori316** [comment]
Oh, fabric added a change in tag system. I need to follow it.

**Comment by pil0lo** [comment]
They said they had changed it, so I downloaded it and put it in.
Even if you search, it doesn't appear in the list.
Do you see it by any chance?

![스크린샷 2024-07-08 210312](https://github.com/Kotori316/InfChest/assets/143984023/1898c404-7279-47dd-b98b-86a56a245e1a)

**Comment by Kotori316** [comment]
Fixed in the latest version

| Recipe | Creative Tab |
|--------|--------|
|<img src="https://github.com/Kotori316/InfChest/assets/28705167/fb597e3d-7291-4fb7-b2ad-ab54f83dd998"> | <img src="https://github.com/Kotori316/InfChest/assets/28705167/4679b0ba-d555-43b2-935e-5d2dec88cdbb"> |
