### ISSUE TITLE
Upload a zh_cn.json (Chinese Simplified)

### ISSUE THREAD

**Issue by tankyap** [Kotori316/InfChest#2]
So I create a zh_cn.json file, which is Chinese Simplified lang file.You can change or use it if you wanted, is on you.
(Since I cannot put the json file here so I write it here)

```
{
    "block.infchest.infchest": "无限箱子",
    "block.infchest.deque": "Deque"
}
```

**Comment by Kotori316** [comment]
Thank you. Added in recent releases.
