### ISSUE TITLE
AE2 Connection and other bugs i discovered

### ISSUE THREAD

**Issue by T-HomesJr** [Kotori316/InfChest#3]
- if the Storage bus is connected to the inf chest, the ae terminal will just show 64 of the item. 
- if you take items out of the system, e.g. the stack, it will still remain on 64 and the inf chest item count doesn't change
- if you put the items back into the terminal it will delete these items if your priority is set to a higher priority than any other
- if you break the inf chest while items are in there (i put simple stone in there), you cannot put any other stone into it

playing this with the modpack valhelsia: enhanced vanilla v1.05 and installed the mod by my own. dunno if this info might help ya troubleshoot this issue

**Comment by Kotori316** [comment]
Is this for Fabric?

**Comment by T-HomesJr** [comment]
> Is this for Fabric?

Yes

**Comment by Kotori316** [comment]
Fixed in [v18.2-fabric](https://www.curseforge.com/minecraft/mc-mods/infchest/files/3637610)
