### ISSUE TITLE
Conflict with the mod WTHIT (Waila)

### ISSUE THREAD

**Issue by Maokeey** [Kotori316/InfChest#4]
The world crashes after I place the chest. It has to do with waila (wthit = What The Hell Is That?) Could you please look into it? Here's the crash log
https://gist.github.com/Maokeey/0d0f5cb9ec73912dbe0fd4c0d3399fdc

Minecraft 1.18.1 Fabric using GDLauncher
Note: I disabled WTHIT tooltip and it didn't crash.
                 However, the mod is quite important. I'd like to keep it. I'd appreciate if you looked into it

**Comment by Kotori316** [comment]
My mod was built with WTHIT(4.1.x) but you have 4.5.4, so there is some differences in WTHIT API, which causes this crash.

I'll make new version built with WTHIT(4.5.4).

**Comment by Kotori316** [comment]
Use 18.2-fabric.
18.3-fabric is for Minecraft 1.18.2 and WTHIT 4.7.x

CurseForge mistakenly registered 18.3-fabric for Minecraft 1.18.1, so I fixed it.

**Comment by Maokeey** [comment]
Didn't know that piece of information. Thank you!
