### ISSUE TITLE
Incompatiblity with AE2

### ISSUE THREAD

**Issue by Zeycox** [Kotori316/InfChest#6]
The game crash when i launch it with AE2 and InfChest. So i make a report at AE2 and they said that you need to update the AE2 version you integrate with.

**Comment by shartte** [comment]
We removed network security in 1.20.1, the Forge cap is now directly for MEStorage

**Comment by Kotori316** [comment]
Thank you for reporting and good advice. I fixed my code to follow changes in AE2(15.0.4-beta)

New versions are released in CurseForge and Modrinth.
