### ISSUE TITLE
Chest getting stuck ~1000 items

### ISSUE THREAD

**Issue by Processhf** [Kotori316/InfChest#9]
For some reason I can't put more items in the chest once it hits ~1000 items. Removing all items and replacing them yields the same result, including multiple different Inf chests with different item types.
![image_2024-03-08_213408460](https://github.com/Kotori316/InfChest/assets/17095896/13ea77bc-2e16-4aca-a1b1-c4aeb56ba32c)

**Comment by Processhf** [comment]
So I've discovered the problem:
Moving the Inf Chest after items are in it will apply an NBT tag to all items inside of it, making it so it can't accept new items without the NBT Tag. The tag is "Charged 0b"

**Comment by Kotori316** [comment]
😕 
I know nothing about `"Charged 0b"` tag. It should be other mod's behavior.
I can do nothing unless I know the mod adding such NBT.

If you want me to fix this issue, please reopen this issue and tell me the minimal reproducible mod list. I don't think it's possible to fix it, however.

**Comment by Processhf** [comment]
It seems to happen on my server even with no other mods installed. Any time I move the chest it gives that tag, however it fixes itself after removing all the items, but it doesn't happen on single player at all. 

The 1 mod that's causing the items to become glitched permanently is called "Pipez". Moving the chest if it was attached to a pipe causes the glitch.

**Comment by Kotori316** [comment]
I want to ask the version. Minecraft 1.20.1 with Forge? If this issue happens when only InfChest is installed, I should take a look.

**Comment by Processhf** [comment]
> I want to ask the version. Minecraft 1.20.1 with Forge? If this issue happens when only InfChest is installed, I should take a look.

Yep 1.20.1 Forge. It only happens with the Inf chest blocks. When the items get "corrupted" they become unstackable with other items of the same type.

**Comment by Kotori316** [comment]
OK. Thank you.

**Comment by Kotori316** [comment]
I tested in my multi player mod with Inf Chest and Pipez, but I wasn't able to reproduce.

Place Inf Chest, then I put 1000 Bottle o' Enchanting, but I found nothing. I can put more items.
